language: objective-c
before_install:
  - brew update
  - brew uninstall xctool && brew install xctool
  - gem install cocoapods -v 0.26.2
  - cd Tests && pod install && cd $TRAVIS_BUILD_DIR
script: "make test"

